build_image:
  image: docker:stable
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t pyguitest .
    - docker run pyguitest pytest --verbose test.py
